warning on test failed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -195,5 +195,7 @@ jobs:
         run: sudo meson install -C build
       - name: test
         run: |
-          xvfb-run -a meson test -C build --verbose --no-stdsplit
+          if ! xvfb-run -a meson test -C build --verbose --no-stdsplit; then
+            echo "::warning test failed"
+          fi
         continue-on-error: true
